### ISSUE TITLE
Module not found: Can't resolve 'slate-react-dnd-plugin'

### ISSUE THREAD

**Issue by askarbayev** [jensneuse/slate-react-dnd-plugin#7] opened 2018-04-06 23:50 UTC
I am trying to use this package. But after following all steps that were given [here] (https://www.npmjs.com/package/slate-react-dnd-plugin) and running my project, I will end up with the error that says 'Module not found: Can't resolve 'slate-react-dnd-plugin'' on my browser.

**Comment by walialu** [comment] 2018-04-06 23:56
Did you follow [this example](https://github.com/jensneuse/slate-react-dnd-plugin#usage)?

**Comment by askarbayev** [comment] 2018-04-07 01:01
Yes, I did

**Comment by walialu** [comment] 2018-04-07 13:40
I'll try to reproduce this, later (this evening GMT+0200) and report back to yo @askarbayev.

**Comment by jensneuse** [comment] 2018-04-09 08:30
We're investigating the error. Seems the published dist dir is empty.

**Comment by askarbayev** [comment] 2018-04-09 13:11
Thank you!
I am looking forward hearing you back.

**Comment by walialu** [comment] 2018-04-10 11:17
Hey @askarbayev, can you try the v1.0.18? @Java-Jonas fixed the issue today :+1:

**Comment by askarbayev** [comment] 2018-04-10 11:55
Thanks, I will try it today

**Comment by walialu** [comment] 2018-04-12 10:12
Hey @askarbayev, any updates on this issues?

I would really like to close this issue, if it didn't persist anymore :)

**Comment by walialu** [comment] 2018-04-13 05:26
I'm closing this and consider this fixed until proven otherwise. Thanks for pointing this out @askarbayev.

**Comment by askarbayev** [comment] 2018-04-13 13:14
Failed to compile
./src/components/Platform/Editor/Forms/TextEditor.js
Module not found: Can't resolve 'slate-react-dnd-plugin' in '/Users/askarbayev1/Desktop/reggora-frontend/src/components/Platform/Editor/Forms'

I am sorry for the late response, this error that I got it again even though I installed the new version

**Comment by walialu** [comment] 2018-04-13 14:25
Hey @askarbayev, can you confirm that the examples (included) in the repo aren't working for you?

**Comment by walialu** [comment] 2018-04-13 14:26
I'm talking about these examples in particular:

https://github.com/jensneuse/slate-react-dnd-plugin/tree/master/example

**Comment by askarbayev** [comment] 2018-04-13 19:46
I tried the example and it is working good. I see that they use this version "slate-react-dnd-plugin": "^1.0.10"
In my case my version is "slate-react-dnd-plugin": "^1.0.18". And I am still getting the error  which is  following
./src/components/Platform/Editor/Forms/TextEditor.js
Module not found: Can't resolve 'slate-react-dnd-plugin' in '/Users/askarbayev1/Desktop/reggora-frontend/src/components/Platform/Editor/Forms'

**Comment by Java-Jonas** [comment] 2018-04-13 20:13
Hey @askarbayev,
It really does seem like the problem is on your end, and not on our's. 
But just to be sure I will try one more time to reproduce the error that you're getting. 
You will hear from me as soon as I have a better idea of what's going wrong! 
So long, 
Happy coding!

**Comment by walialu** [comment] 2018-04-14 12:14
Hey @askarbayev,

Can you check if the latest release fixes your issue?

v1.0.21 has been built here: https://git.superevilmegaco.com/reactjs/slate-react-dnd-plugin/-/jobs/51 and should work as expected.

**Comment by askarbayev** [comment] 2018-04-17 13:07
Hi,

I tried to install a new version of this package. So far, I just tried
import the package and it works with no error unlike previous.
Thank you for your help!



On Sat, Apr 14, 2018 at 8:14 AM, Marco Kellershoff <notifications@github.com

**Comment by walialu** [comment] 2018-04-17 13:53
Alright, I'll close this issue and if something pops up again, we can either re-open this or open up another one.

Thanks @askarbayev!

**Closed by walialu** 2018-04-17 13:53 UTC
Labels: help wanted, question
